# Generated by Django 3.1.7 on 2023-05-06 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('complement', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('NOIVO', 'Noivo'), ('FORNECEDOR', 'Supplier')], default='NOIVO', max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(choices=[('Cerimônia e Recepção', 'Cerymony Reception'), ('Buffet e Catering', 'Buffet Catering'), ('Decoração', 'Decoration'), ('Fotografia e Vídeo', 'Photography Video'), ('Música e Entretenimento', 'Music Enterteinment'), ('Vestido e Traje', 'Wedding Dress Attire'), ('Convites e Papelaria', 'Invitations Paper Goods'), ('Cabelo e Maquiagem', 'Hair Makeup'), ('Transporte', 'Transportation'), ('Lembrancinhas e Presentes', 'Souvenirs Gifts'), ('Outros', 'Others')], default='Outros', max_length=100)),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.customuser')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='SupplierServicePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
            options={
                'verbose_name': 'Foto do Fornecedor',
                'verbose_name_plural': 'Fotos dos Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Noivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.customuser')),
            ],
            options={
                'verbose_name': 'Noivo',
                'verbose_name_plural': 'Noivos',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('size', models.CharField(choices=[('Elopment Wedding', 'Elopment Wedding'), ('Mini Wedding', 'Mini Wedding'), ('Casamento Pequeno', 'Small Wedding'), ('Casamento Médio', 'Medium Wedding'), ('Casamento Grande', 'Big Wedding'), ('Mega Wedding', 'Mega Wedding'), ('Destination Wedding', 'Destination Wedding')], default='Casamento Médio', max_length=100)),
                ('style', models.CharField(choices=[('Classico / Tradicional', 'Classic Traditional'), ('Moderno / Minimalista', 'Modern Minimalist'), ('Vintage / Rustico', 'Vintage Rustic'), ('Praia / Campo', 'Beach Countryside'), ('Temático', 'Thematic')], default='Classico / Tradicional', max_length=100)),
                ('bride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bride', to='app.noivo')),
                ('groom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groom', to='app.noivo')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
