# Generated by Django 3.2.16 on 2023-05-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
