# Generated by Django 3.2.16 on 2023-05-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_artifact_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
