# Generated by Django 3.2.16 on 2023-05-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
