# Generated by Django 3.2.16 on 2023-05-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_event_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='color2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='color3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='color4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
